const MUSCLES = [
 {id:'trapezio',member:'superior',region:'Cintura escapular',name:'Trapézio',origin:'Linha nucal superior, protuberância occipital externa, ligamento nucal e processos espinhosos de C7 a T12.',insertion:'Terço lateral da clavícula, acrômio e espinha da escápula.',actions:'Elevação, retração, depressão e rotação superior da escápula; auxilia na extensão cervical.',innervation:'Nervo acessório (XI) e ramos cervicais C3-C4.',application:'Remadas, encolhimento, estabilização escapular em puxadas, postura e controle da cintura escapular.',demo:'Mostre a grande lâmina posterior. Peça ao aluno para diferenciar fibras superiores, médias e inferiores e relacionar cada direção de fibra ao movimento da escápula.',questions:['Qual porção eleva a escápula?','Qual movimento escapular ocorre na remada?','Por que ele é importante para postura?']},
 {id:'deltoide',member:'superior',region:'Ombro',name:'Deltoide',origin:'Terço lateral da clavícula, acrômio e espinha da escápula.',insertion:'Tuberosidade deltoidea do úmero.',actions:'Abdução do braço; fibras anteriores fazem flexão e rotação medial; fibras posteriores fazem extensão e rotação lateral.',innervation:'Nervo axilar.',application:'Elevação lateral, desenvolvimento, arremesso, natação e estabilização dinâmica do ombro.',demo:'Mostre o músculo envolvendo o ombro como uma capa. Explique que a porção média é a principal para abdução acima dos primeiros graus.',questions:['Qual nervo inerva o deltoide?','Qual porção faz extensão do ombro?','Em que exercício a porção média é muito recrutada?']},
 {id:'supraespinal',member:'superior',region:'Manguito rotador',name:'Supraespinal',origin:'Fossa supraespinal da escápula.',insertion:'Faceta superior do tubérculo maior do úmero.',actions:'Inicia a abdução do braço e estabiliza a cabeça do úmero.',innervation:'Nervo supraescapular.',application:'Fundamental em abdução inicial, esportes acima da cabeça e prevenção de impacto subacromial.',demo:'Mostre o trajeto superior à espinha da escápula em direção ao tubérculo maior. Relacione com a estabilização glenoumeral.',questions:['Qual movimento ele inicia?','Por que faz parte do manguito rotador?','Qual lesão é comum nessa região?']},
 {id:'infraespinal',member:'superior',region:'Manguito rotador',name:'Infraespinal',origin:'Fossa infraespinal da escápula.',insertion:'Faceta média do tubérculo maior do úmero.',actions:'Rotação lateral do braço e estabilização do ombro.',innervation:'Nervo supraescapular.',application:'Importante em arremesso, natação, vôlei e exercícios de rotação externa.',demo:'Mostre abaixo da espinha da escápula. Peça ao aluno para simular rotação lateral do ombro.',questions:['Qual ação principal?','Qual nervo?','Como ele protege a articulação glenoumeral?']},
 {id:'redondo-menor',member:'superior',region:'Manguito rotador',name:'Redondo menor',origin:'Borda lateral da escápula.',insertion:'Faceta inferior do tubérculo maior do úmero.',actions:'Rotação lateral e adução fraca do braço; estabilização glenoumeral.',innervation:'Nervo axilar.',application:'Controle posterior do ombro em arremessos e estabilidade em exercícios de puxada.',demo:'Mostre sua posição inferior ao infraespinal e superior ao redondo maior.',questions:['Como diferenciar redondo menor de redondo maior?','Qual nervo inerva?','Qual ação compartilha com infraespinal?']},
 {id:'subescapular',member:'superior',region:'Manguito rotador',name:'Subescapular',origin:'Fossa subescapular.',insertion:'Tubérculo menor do úmero.',actions:'Rotação medial e adução do braço; estabilização da cabeça umeral.',innervation:'Nervos subescapulares superior e inferior.',application:'Rotação interna em natação, arremesso, empurrões e estabilização anterior do ombro.',demo:'Mostre na face costal da escápula. Explique que é o único manguito anterior.',questions:['Qual tubérculo recebe sua inserção?','Qual ação principal?','Por que é estabilizador anterior?']},
 {id:'biceps-braquial',member:'superior',region:'Braço anterior',name:'Bíceps braquial',origin:'Cabeça curta: processo coracoide. Cabeça longa: tubérculo supraglenoidal da escápula.',insertion:'Tuberosidade do rádio e aponeurose bicipital.',actions:'Supinação do antebraço, flexão do cotovelo e auxílio na flexão do ombro.',innervation:'Nervo musculocutâneo.',application:'Rosca direta, puxadas, barra, tração e movimentos com supinação.',demo:'Mostre as duas cabeças no braço anterior e a inserção radial. Relacione supinação com tuberosidade do rádio.',questions:['Por que ele é forte supinador?','Qual cabeça cruza a articulação do ombro?','Qual exercício evidencia sua ação?']},
 {id:'braquial',member:'superior',region:'Braço anterior',name:'Braquial',origin:'Metade distal da face anterior do úmero.',insertion:'Tuberosidade da ulna e processo coronoide.',actions:'Principal flexor do cotovelo.',innervation:'Nervo musculocutâneo; contribuição radial em parte lateral.',application:'Flexão de cotovelo em puxadas, roscas e movimentos de tração independentemente da posição do antebraço.',demo:'Mostre profundo ao bíceps. Destaque que atua mesmo em pronação.',questions:['Por que é considerado principal flexor do cotovelo?','Ele faz supinação?','Qual osso recebe sua inserção?']},
 {id:'triceps-braquial',member:'superior',region:'Braço posterior',name:'Tríceps braquial',origin:'Cabeça longa: tubérculo infraglenoidal. Cabeça lateral: face posterior do úmero acima do sulco radial. Cabeça medial: face posterior do úmero abaixo do sulco radial.',insertion:'Olécrano da ulna.',actions:'Extensão do cotovelo; cabeça longa auxilia na extensão e adução do ombro.',innervation:'Nervo radial.',application:'Supino, flexão de braço, mergulho, arremesso, empurrões e estabilização do cotovelo.',demo:'Mostre as três cabeças na região posterior do braço e a convergência para o olécrano.',questions:['Qual cabeça cruza o ombro?','Qual movimento no cotovelo?','Em qual exercício ele é agonista?']},
 {id:'pronador-redondo',member:'superior',region:'Antebraço anterior',name:'Pronador redondo',origin:'Epicôndilo medial do úmero e processo coronoide da ulna.',insertion:'Face lateral do rádio.',actions:'Pronação do antebraço e flexão fraca do cotovelo.',innervation:'Nervo mediano.',application:'Movimentos de giro do antebraço, pegadas, esportes com raquete e estabilização em empurrões.',demo:'Mostre a direção oblíqua do epicôndilo medial até o rádio.',questions:['Qual movimento ele produz no rádio?','Qual nervo passa entre suas cabeças?','Como testar pronação?']},
 {id:'flexor-radial-carpo',member:'superior',region:'Antebraço anterior',name:'Flexor radial do carpo',origin:'Epicôndilo medial do úmero.',insertion:'Bases do 2º e 3º metacarpais.',actions:'Flexão e abdução radial do punho.',innervation:'Nervo mediano.',application:'Pegada, flexão de punho, apoio em exercícios e controle do punho em esportes.',demo:'Mostre no lado radial do antebraço anterior e siga o tendão até a mão.',questions:['Qual desvio do punho ele auxilia?','Qual epicôndilo dá origem?','Como aparece na pegada?']},
 {id:'flexor-ulnar-carpo',member:'superior',region:'Antebraço anterior',name:'Flexor ulnar do carpo',origin:'Epicôndilo medial do úmero, olécrano e borda posterior da ulna.',insertion:'Pisiforme, hamato e base do 5º metacarpal.',actions:'Flexão e adução ulnar do punho.',innervation:'Nervo ulnar.',application:'Estabilização de punho, pegada forte, exercícios de tração e esportes de combate.',demo:'Mostre a margem ulnar do antebraço anterior. Relacione com desvio ulnar.',questions:['Qual nervo inerva?','Qual osso sesamoide recebe sua inserção?','Qual movimento no punho?']},
 {id:'flexor-superficial-dedos',member:'superior',region:'Antebraço anterior',name:'Flexor superficial dos dedos',origin:'Epicôndilo medial, processo coronoide e margem anterior do rádio.',insertion:'Falanges médias dos dedos 2 a 5.',actions:'Flexão das interfalângicas proximais, metacarpofalângicas e punho.',innervation:'Nervo mediano.',application:'Preensão, escalada, musculação, ginástica e esportes com implementos.',demo:'Mostre tendões indo aos dedos. Explique diferença entre flexão superficial e profunda.',questions:['Quais falanges recebe sua inserção?','Qual articulação flexiona principalmente?','Como se relaciona com pegada?']},
 {id:'flexor-profundo-dedos',member:'superior',region:'Antebraço profundo',name:'Flexor profundo dos dedos',origin:'Face anterior e medial da ulna e membrana interóssea.',insertion:'Falanges distais dos dedos 2 a 5.',actions:'Flexão das interfalângicas distais e auxilia na flexão dos dedos e punho.',innervation:'Metade lateral: nervo interósseo anterior/mediano. Metade medial: nervo ulnar.',application:'Força de ponta dos dedos, escalada, judô, pegadas finas e sustentação de carga.',demo:'Mostre camada profunda e explique que alcança falanges distais.',questions:['Qual articulação flexiona de modo mais característico?','Por que tem dupla inervação?','Em que esporte é muito exigido?']},
 {id:'extensor-dedos',member:'superior',region:'Antebraço posterior',name:'Extensor dos dedos',origin:'Epicôndilo lateral do úmero.',insertion:'Expansões extensoras dos dedos 2 a 5.',actions:'Extensão dos dedos e punho.',innervation:'Nervo interósseo posterior, ramo do radial.',application:'Controle da mão aberta, estabilização do punho, esportes de raquete e liberação da pegada.',demo:'Mostre tendões dorsais para os dedos e a expansão extensora.',questions:['Qual epicôndilo dá origem?','Qual compartimento?','Qual nervo?']},
 {id:'braquiorradial',member:'superior',region:'Antebraço lateral',name:'Braquiorradial',origin:'Crista supracondilar lateral do úmero.',insertion:'Processo estiloide do rádio.',actions:'Flexão do cotovelo, especialmente com antebraço em posição neutra.',innervation:'Nervo radial.',application:'Rosca martelo, puxadas e movimentos de transporte de carga.',demo:'Mostre no limite lateral do antebraço e relacione com posição neutra.',questions:['Qual exercício evidencia o braquiorradial?','Ele é flexor ou extensor do cotovelo?','Qual nervo inerva?']},
 {id:'gluteo-maximo',member:'inferior',region:'Quadril posterior',name:'Glúteo máximo',origin:'Ílio posterior, sacro, cóccix e ligamento sacrotuberal.',insertion:'Trato iliotibial e tuberosidade glútea do fêmur.',actions:'Extensão e rotação lateral do quadril; auxilia na estabilidade da pelve.',innervation:'Nervo glúteo inferior.',application:'Agachamento, levantamento terra, subida de escada, corrida, salto e potência do quadril.',demo:'Mostre a massa posterior do quadril e sua direção para trato iliotibial/fêmur.',questions:['Qual movimento principal?','Em qual fase do agachamento ele atua mais?','Qual nervo inerva?']},
 {id:'gluteo-medio',member:'inferior',region:'Quadril lateral',name:'Glúteo médio',origin:'Face glútea do ílio entre linhas glúteas anterior e posterior.',insertion:'Face lateral do trocânter maior do fêmur.',actions:'Abdução e rotação medial do quadril; estabiliza a pelve no apoio unipodal.',innervation:'Nervo glúteo superior.',application:'Marcha, corrida, equilíbrio unipodal, prevenção de valgo dinâmico e estabilidade pélvica.',demo:'Mostre na lateral do quadril. Explique teste de Trendelenburg e apoio em uma perna.',questions:['Por que estabiliza a pelve?','Qual sinal aparece na fraqueza?','Qual nervo?']},
 {id:'iliopsoas',member:'inferior',region:'Quadril anterior',name:'Iliopsoas',origin:'Psoas maior: corpos e processos transversos lombares. Ilíaco: fossa ilíaca.',insertion:'Trocânter menor do fêmur.',actions:'Principal flexor do quadril; auxilia na rotação lateral e flexão do tronco.',innervation:'Ramos lombares para psoas e nervo femoral para ilíaco.',application:'Corrida, chute, subida de escada, elevação de joelho e exercícios abdominais com flexão de quadril.',demo:'Mostre trajeto profundo anterior até o trocânter menor. Explique sua importância na passada.',questions:['Qual é a inserção comum?','Em que movimento esportivo é evidente?','Por que pode influenciar postura lombar?']},
 {id:'reto-femoral',member:'inferior',region:'Coxa anterior',name:'Reto femoral',origin:'Espinha ilíaca ântero-inferior e região superior ao acetábulo.',insertion:'Patela e tuberosidade da tíbia via ligamento patelar.',actions:'Extensão do joelho e flexão do quadril.',innervation:'Nervo femoral.',application:'Chute, corrida, agachamento, salto e exercícios de cadeira extensora.',demo:'Mostre que cruza quadril e joelho. Compare com vastos, que cruzam principalmente o joelho.',questions:['Por que é biarticular?','Qual ação no quadril?','Qual movimento no chute?']},
 {id:'vasto-medial',member:'inferior',region:'Coxa anterior',name:'Vasto medial',origin:'Linha intertrocantérica e lábio medial da linha áspera.',insertion:'Patela e tuberosidade da tíbia via ligamento patelar.',actions:'Extensão do joelho e estabilização medial da patela.',innervation:'Nervo femoral.',application:'Agachamento, subida de escada, reabilitação patelofemoral e controle da extensão do joelho.',demo:'Mostre a porção medial em gota próxima ao joelho. Relacione com alinhamento patelar.',questions:['Qual função na patela?','Qual nervo?','Em que exercício é recrutado?']},
 {id:'vasto-lateral',member:'inferior',region:'Coxa anterior',name:'Vasto lateral',origin:'Trocânter maior e lábio lateral da linha áspera.',insertion:'Patela e tuberosidade da tíbia via ligamento patelar.',actions:'Extensão do joelho.',innervation:'Nervo femoral.',application:'Potência em agachamento, salto, corrida e leg press.',demo:'Mostre a grande massa lateral da coxa anterior.',questions:['Qual grupo muscular integra?','Qual movimento produz?','Qual antagonista na flexão do joelho?']},
 {id:'sartorio',member:'inferior',region:'Coxa anterior/medial',name:'Sartório',origin:'Espinha ilíaca ântero-superior.',insertion:'Pata de ganso na face medial proximal da tíbia.',actions:'Flexão, abdução e rotação lateral do quadril; flexão do joelho.',innervation:'Nervo femoral.',application:'Movimento de cruzar as pernas, mudanças de direção e estabilização medial do joelho.',demo:'Mostre trajeto oblíquo da EIAS até a tíbia medial.',questions:['Por que é chamado músculo do costureiro?','Qual inserção comum participa?','Ele cruza quais articulações?']},
 {id:'biceps-femoral',member:'inferior',region:'Coxa posterior',name:'Bíceps femoral',origin:'Cabeça longa: tuberosidade isquiática. Cabeça curta: linha áspera do fêmur.',insertion:'Cabeça da fíbula.',actions:'Flexão do joelho, extensão do quadril pela cabeça longa e rotação lateral da perna.',innervation:'Cabeça longa: porção tibial do ciático. Cabeça curta: porção fibular comum do ciático.',application:'Sprint, desaceleração, levantamento terra, flexora e estabilização posterior do joelho.',demo:'Mostre lateralmente na coxa posterior e siga até a cabeça da fíbula.',questions:['Qual cabeça é biarticular?','Qual inserção lateral?','Por que sofre lesão em sprint?']},
 {id:'semitendineo',member:'inferior',region:'Coxa posterior',name:'Semitendíneo',origin:'Tuberosidade isquiática.',insertion:'Pata de ganso na face medial proximal da tíbia.',actions:'Extensão do quadril, flexão do joelho e rotação medial da perna.',innervation:'Porção tibial do nervo ciático.',application:'Corrida, ponte, levantamento terra, controle da desaceleração e estabilidade medial.',demo:'Mostre tendão longo medial posterior e relação com pata de ganso.',questions:['Qual rotação da perna realiza?','Qual inserção comum?','Qual nervo?']},
 {id:'semimembranaceo',member:'inferior',region:'Coxa posterior',name:'Semimembranáceo',origin:'Tuberosidade isquiática.',insertion:'Côndilo medial da tíbia.',actions:'Extensão do quadril, flexão do joelho e rotação medial da perna.',innervation:'Porção tibial do nervo ciático.',application:'Controle posterior da coxa, corrida, estabilização do joelho e movimentos de desaceleração.',demo:'Mostre profundo/medial ao semitendíneo.',questions:['Como diferenciar do semitendíneo?','Qual inserção?','Qual ação no joelho?']},
 {id:'adutor-longo',member:'inferior',region:'Coxa medial',name:'Adutor longo',origin:'Corpo do púbis inferior à crista púbica.',insertion:'Terço médio da linha áspera do fêmur.',actions:'Adução do quadril; auxilia flexão do quadril.',innervation:'Nervo obturatório.',application:'Futebol, mudança de direção, corrida lateral, estabilização pélvica e prevenção de pubalgia.',demo:'Mostre na região medial da coxa, superficial.',questions:['Qual nervo inerva os adutores?','Em que esporte é muito exigido?','Qual movimento principal?']},
 {id:'adutor-magno',member:'inferior',region:'Coxa medial',name:'Adutor magno',origin:'Ramo inferior do púbis, ramo do ísquio e tuberosidade isquiática.',insertion:'Linha áspera e tubérculo do adutor no fêmur.',actions:'Adução do quadril; porção isquiotibial auxilia extensão do quadril.',innervation:'Nervo obturatório e porção tibial do nervo ciático.',application:'Estabilização em agachamentos, mudanças de direção, corrida e exercícios de adução.',demo:'Mostre como grande massa medial profunda e explique sua dupla função.',questions:['Por que tem dupla inervação?','Qual porção ajuda na extensão do quadril?','Qual abertura anatômica se relaciona com vasos femorais?']},
 {id:'tibial-anterior',member:'inferior',region:'Perna anterior',name:'Tibial anterior',origin:'Côndilo lateral e face lateral da tíbia; membrana interóssea.',insertion:'Cuneiforme medial e base do 1º metatarsal.',actions:'Dorsiflexão e inversão do pé.',innervation:'Nervo fibular profundo.',application:'Marcha, corrida, controle do pé no contato com o solo e prevenção de queda do pé.',demo:'Mostre anterior à tíbia e seu tendão indo ao lado medial do pé.',questions:['Qual nervo?','Qual movimento evita que o pé arraste?','Qual antagonista na flexão plantar?']},
 {id:'fibular-longo',member:'inferior',region:'Perna lateral',name:'Fibular longo',origin:'Cabeça e face lateral superior da fíbula.',insertion:'Base do 1º metatarsal e cuneiforme medial pela planta do pé.',actions:'Eversão e flexão plantar; sustenta arco transverso do pé.',innervation:'Nervo fibular superficial.',application:'Equilíbrio, corrida, mudanças de direção e estabilidade lateral do tornozelo.',demo:'Mostre na lateral da perna e explique o trajeto plantar até o primeiro raio.',questions:['Qual movimento lateral realiza?','Qual nervo?','Por que ajuda na estabilidade do tornozelo?']},
 {id:'gastrocnemio',member:'inferior',region:'Perna posterior superficial',name:'Gastrocnêmio',origin:'Côndilos medial e lateral do fêmur.',insertion:'Calcâneo pelo tendão calcâneo.',actions:'Flexão plantar do tornozelo e flexão do joelho.',innervation:'Nervo tibial.',application:'Salto, corrida, caminhada, ficar na ponta dos pés e propulsão.',demo:'Mostre as duas cabeças na panturrilha. Explique que cruza joelho e tornozelo.',questions:['Por que é biarticular?','Qual tendão comum utiliza?','Quando trabalha mais: joelho estendido ou flexionado?']},
 {id:'soleo',member:'inferior',region:'Perna posterior profunda',name:'Sóleo',origin:'Linha do sóleo na tíbia e face posterior da fíbula.',insertion:'Calcâneo pelo tendão calcâneo.',actions:'Flexão plantar do tornozelo; importante músculo postural.',innervation:'Nervo tibial.',application:'Manutenção da postura em pé, caminhada, corrida de resistência e panturrilha sentado.',demo:'Mostre profundo ao gastrocnêmio. Compare sua atuação com joelho flexionado.',questions:['Por que é importante para postura?','Qual exercício o evidencia?','Qual nervo?']},
 {id:'tibial-posterior',member:'inferior',region:'Perna posterior profunda',name:'Tibial posterior',origin:'Membrana interóssea, tíbia e fíbula posteriores.',insertion:'Navicular, cuneiformes, cuboide e bases dos metatarsais.',actions:'Inversão e flexão plantar; sustenta arco medial do pé.',innervation:'Nervo tibial.',application:'Controle do arco plantar, corrida, marcha e prevenção de pronação excessiva.',demo:'Mostre profundamente e relacione com suporte do arco medial.',questions:['Qual arco sustenta?','Qual movimento faz no pé?','Qual nervo?']}
];

const DB_NAME='muscleAtlasDB'; const STORE='records'; let db; let deferredPrompt=null;
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=e=>{e.target.result.createObjectStore(STORE,{keyPath:'id'});};req.onsuccess=e=>{db=e.target.result;resolve(db)};req.onerror=()=>reject(req.error);});}
function getRecord(id){return new Promise(resolve=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result||{id,note:'',photos:[]});req.onerror=()=>resolve({id,note:'',photos:[]});});}
function putRecord(record){return new Promise(resolve=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(record);tx.oncomplete=resolve;});}
function allRecords(){return new Promise(resolve=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>resolve([]);});}
function fileToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
function normalize(t){return (t||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}

function setupInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('btnInstall').disabled=false;});document.getElementById('btnInstall').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt(); await deferredPrompt.userChoice; deferredPrompt=null;} else alert('Para instalar: abra o menu do navegador e toque em “Adicionar à tela inicial”.');};}
function renderFilters(){const select=document.getElementById('filterRegion');[...new Set(MUSCLES.map(m=>m.region))].sort().forEach(r=>{const o=document.createElement('option');o.value=r;o.textContent=r;select.appendChild(o);});}
function renderStats(list){document.getElementById('stats').innerHTML=`<div class="stat"><b>${MUSCLES.length}</b>músculos no roteiro</div><div class="stat"><b>${list.length}</b>exibidos agora</div><div class="stat"><b>${MUSCLES.filter(m=>m.member==='superior').length}</b>membro superior</div><div class="stat"><b>${MUSCLES.filter(m=>m.member==='inferior').length}</b>membro inferior</div>`;}
async function render(){const q=normalize(document.getElementById('search').value);const member=document.getElementById('filterMember').value;const region=document.getElementById('filterRegion').value;let list=MUSCLES.filter(m=>{const blob=normalize(Object.values(m).flat().join(' '));return (!q||blob.includes(q))&&(member==='todos'||m.member===member)&&(region==='todas'||m.region===region);});renderStats(list);const wrap=document.getElementById('muscleList');wrap.innerHTML='';const tpl=document.getElementById('muscleTemplate');for(const m of list){const node=tpl.content.cloneNode(true);const card=node.querySelector('.muscle-card');card.dataset.id=m.id;node.querySelector('.member').textContent=m.member==='superior'?'Membro superior':'Membro inferior';node.querySelector('.region').textContent=m.region;node.querySelector('.muscle-name').textContent=m.name;node.querySelector('.origin').textContent=m.origin;node.querySelector('.insertion').textContent=m.insertion;node.querySelector('.actions-text').textContent=m.actions;node.querySelector('.innervation').textContent=m.innervation;node.querySelector('.application').textContent=m.application;node.querySelector('.demo').textContent=m.demo;node.querySelector('.questions').innerHTML=m.questions.map(x=>`<li>${x}</li>`).join('');const rec=await getRecord(m.id);const note=node.querySelector('.note');note.value=rec.note||'';const gallery=node.querySelector('.gallery');function drawGallery(){gallery.innerHTML=(rec.photos||[]).map((p,i)=>`<div class="photo"><img src="${p.data}" alt="Foto anexada de ${m.name}"><button data-i="${i}" title="Remover">×</button></div>`).join('');gallery.querySelectorAll('button').forEach(b=>b.onclick=async()=>{rec.photos.splice(Number(b.dataset.i),1);await putRecord(rec);drawGallery();});}
drawGallery();node.querySelector('.toggle').onclick=()=>{card.classList.toggle('open');node.querySelector('.toggle').textContent=card.classList.contains('open')?'Fechar':'Abrir';};note.oninput=async()=>{rec.note=note.value;await putRecord(rec);};async function addFiles(files,source){for(const file of files){if(!file.type.startsWith('image/')) continue;const data=await fileToDataURL(file);rec.photos=rec.photos||[];rec.photos.push({data,name:file.name||source,date:new Date().toISOString(),source});}await putRecord(rec);drawGallery();}
node.querySelector('.cameraInput').onchange=e=>addFiles(e.target.files,'camera');node.querySelector('.fileInput').onchange=e=>addFiles(e.target.files,'anexo');node.querySelector('.clearPhotos').onclick=async()=>{if(confirm('Remover todas as fotos deste músculo?')){rec.photos=[];await putRecord(rec);drawGallery();}};wrap.appendChild(node);} }
function setupExportImport(){document.getElementById('btnExport').onclick=async()=>{const records=await allRecords();const payload={app:'Atlas Sistema Muscular',version:1,exportedAt:new Date().toISOString(),records};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='backup-atlas-sistema-muscular.json';a.click();URL.revokeObjectURL(a.href);};document.getElementById('importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();const payload=JSON.parse(text);for(const r of payload.records||[]) await putRecord(r);alert('Dados importados com sucesso.');render();};}
function setupPDF(){document.getElementById('btnPdf').onclick=()=>{document.querySelectorAll('.muscle-card').forEach(c=>c.classList.add('open'));setTimeout(()=>window.print(),200);};}
async function boot(){await openDB();renderFilters();setupInstall();setupPDF();setupExportImport();document.getElementById('search').oninput=render;document.getElementById('filterMember').onchange=render;document.getElementById('filterRegion').onchange=render;await render();if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});} }
boot();
